// Mock data layer for Amit Furniture Admin
// This simulates the backend API. Replace with real API calls when backend is connected.

import type {
  User,
  Customer,
  Enquiry,
  Quotation,
  Project,
  Task,
  Payment,
  Invoice,
  CalendarEvent,
  Communication,
  Document,
  ActivityLog,
  Notification,
} from "./types";

/* ============================================================
 * USERS & ROLES
 * ============================================================ */

export const users: User[] = [
  {
    id: "u1",
    name: "Amit Kumar Sharma",
    email: "amit@amitfurniture.com",
    phone: "+91 98765 43210",
    roleId: "r1",
    roleName: "Super Admin",
    status: "active",
    avatarUrl: null,
    lastLoginAt: new Date().toISOString(),
    createdAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "u2",
    name: "Priya Das",
    email: "priya@amitfurniture.com",
    phone: "+91 98765 43211",
    roleId: "r2",
    roleName: "Manager",
    status: "active",
    avatarUrl: null,
    lastLoginAt: new Date(Date.now() - 3600000).toISOString(),
    createdAt: "2025-02-10T10:00:00Z",
  },
  {
    id: "u3",
    name: "Rahul Verma",
    email: "rahul@amitfurniture.com",
    phone: "+91 98765 43212",
    roleId: "r3",
    roleName: "Sales Staff",
    status: "active",
    avatarUrl: null,
    lastLoginAt: new Date(Date.now() - 7200000).toISOString(),
    createdAt: "2025-03-05T10:00:00Z",
  },
  {
    id: "u4",
    name: "Sneha Gupta",
    email: "sneha@amitfurniture.com",
    phone: "+91 98765 43213",
    roleId: "r4",
    roleName: "Accountant",
    status: "active",
    avatarUrl: null,
    lastLoginAt: new Date(Date.now() - 86400000).toISOString(),
    createdAt: "2025-03-15T10:00:00Z",
  },
  {
    id: "u5",
    name: "Bikash Rai",
    email: "bikash@amitfurniture.com",
    phone: "+91 98765 43214",
    roleId: "r5",
    roleName: "Workshop Lead",
    status: "active",
    avatarUrl: null,
    lastLoginAt: new Date(Date.now() - 172800000).toISOString(),
    createdAt: "2025-04-01T10:00:00Z",
  },
];

/* ============================================================
 * CUSTOMERS
 * ============================================================ */

export const customers: Customer[] = [
  {
    id: "c1",
    name: "Rahul Sharma",
    email: "rahul.sharma@example.com",
    phone: "+91 98300 11223",
    alternatePhone: "+91 98300 11224",
    preferredContact: "phone",
    company: null,
    source: "website",
    totalBusinessValue: "185000",
    notes: "Referred by Mr. Banerjee. Prefers teak wood finish.",
    createdAt: "2025-08-12T09:30:00Z",
    address: {
      line1: "42, Hill Cart Road",
      city: "Siliguri",
      district: "Darjeeling",
      state: "West Bengal",
      pincode: "734001",
    },
  },
  {
    id: "c2",
    name: "Priya Das",
    email: "priya.das@example.com",
    phone: "+91 98300 22334",
    preferredContact: "whatsapp",
    company: "Das Interiors",
    source: "referral",
    totalBusinessValue: "320000",
    notes: "Interior designer. Regular client.",
    createdAt: "2025-07-04T11:15:00Z",
    address: {
      line1: "15, Sevoke Road",
      city: "Siliguri",
      state: "West Bengal",
      pincode: "734001",
    },
  },
  {
    id: "c3",
    name: "Amit Roy",
    email: "amit.roy@example.com",
    phone: "+91 98300 33445",
    preferredContact: "phone",
    source: "walk-in",
    totalBusinessValue: "95000",
    createdAt: "2025-09-18T14:20:00Z",
    address: {
      line1: "78, Hakim Para",
      city: "Siliguri",
      state: "West Bengal",
      pincode: "734001",
    },
  },
  {
    id: "c4",
    name: "Sanjay Gupta",
    email: "sanjay.gupta@example.com",
    phone: "+91 98300 44556",
    preferredContact: "email",
    company: "Gupta Enterprises",
    source: "website",
    totalBusinessValue: "450000",
    notes: "Corporate client. Requires GST invoice.",
    createdAt: "2025-06-22T10:45:00Z",
    address: {
      line1: "23, Burdwan Road",
      city: "Siliguri",
      state: "West Bengal",
      pincode: "734001",
    },
  },
  {
    id: "c5",
    name: "Neha Sharma",
    email: "neha.sharma@example.com",
    phone: "+91 98300 55667",
    preferredContact: "whatsapp",
    source: "referral",
    totalBusinessValue: "125000",
    createdAt: "2025-10-05T16:30:00Z",
    address: {
      line1: "12, Pradhan Nagar",
      city: "Siliguri",
      state: "West Bengal",
      pincode: "734003",
    },
  },
  {
    id: "c6",
    name: "Rajesh Agarwal",
    email: "rajesh.agarwal@example.com",
    phone: "+91 98300 66778",
    preferredContact: "phone",
    company: "Agarwal Hotels",
    source: "website",
    totalBusinessValue: "780000",
    createdAt: "2025-05-14T08:20:00Z",
    address: {
      line1: "56, Hospital Road",
      city: "Jalpaiguri",
      state: "West Bengal",
      pincode: "735101",
    },
  },
  {
    id: "c7",
    name: "Kavita Bose",
    email: "kavita.bose@example.com",
    phone: "+91 98300 77889",
    preferredContact: "phone",
    source: "website",
    totalBusinessValue: "65000",
    createdAt: "2025-11-02T13:10:00Z",
    address: {
      line1: "34, Darjeeling More",
      city: "Darjeeling",
      state: "West Bengal",
      pincode: "734101",
    },
  },
  {
    id: "c8",
    name: "Suresh Thapa",
    email: "suresh.thapa@example.com",
    phone: "+91 98300 88990",
    preferredContact: "whatsapp",
    source: "walk-in",
    totalBusinessValue: "0",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    address: {
      line1: "8, Laden La Road",
      city: "Darjeeling",
      state: "West Bengal",
      pincode: "734101",
    },
  },
];

/* ============================================================
 * ENQUIRIES
 * ============================================================ */

export const enquiries: Enquiry[] = [
  {
    id: "e1",
    number: "AF-E-2026-0001",
    customerId: "c1",
    customerName: "Rahul Sharma",
    service: "Custom Wardrobe",
    category: "furniture",
    requirement: "3-door sliding wardrobe for master bedroom, 8ft wide × 7ft tall",
    description: "Looking for a modern sliding wardrobe with loft storage. Teak finish preferred. Includes 2 drawers, mirror, and internal LED lighting.",
    dimensions: "8ft × 7ft × 2ft",
    material: "Teak wood with plywood interior",
    designPreference: "Modern minimal with brushed brass handles",
    budget: "85000",
    expectedCompletion: "2026-02-15",
    status: "quoted",
    priority: "high",
    assignedUserId: "u2",
    assignedUserName: "Priya Das",
    followUpDate: "2026-01-20",
    source: "website",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "e2",
    number: "AF-E-2026-0002",
    customerId: "c2",
    customerName: "Priya Das",
    service: "Modular Kitchen",
    category: "furniture",
    requirement: "L-shaped modular kitchen for 12×10 ft space",
    description: "Complete modular kitchen with tall unit, base cabinets, wall units, chimney hood, and breakfast counter. Acrylic finish.",
    dimensions: "12ft × 10ft L-shape",
    material: "Marine plywood with acrylic shutters",
    designPreference: "Contemporary with grey and white combination",
    budget: "280000",
    expectedCompletion: "2026-03-30",
    status: "approved",
    priority: "urgent",
    assignedUserId: "u2",
    assignedUserName: "Priya Das",
    source: "referral",
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "e3",
    number: "AF-E-2026-0003",
    customerId: "c3",
    customerName: "Amit Roy",
    service: "Wooden Sofa",
    category: "furniture",
    requirement: "5-seater solid wood sofa set with centre table",
    description: "3+1+1 configuration. Cushioned seats with wooden armrests.",
    dimensions: "Standard 5-seater",
    material: "Sheesham wood",
    budget: "65000",
    expectedCompletion: "2026-02-28",
    status: "new",
    priority: "medium",
    assignedUserId: "u3",
    assignedUserName: "Rahul Verma",
    source: "walk-in",
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: "e4",
    number: "AF-E-2026-0004",
    customerId: "c4",
    customerName: "Sanjay Gupta",
    service: "Office Furniture",
    category: "furniture",
    requirement: "Complete office furniture for 20 workstations",
    description: "Workstations, executive cabin, conference table for 10, reception desk, and storage units.",
    dimensions: "Office area 2400 sqft",
    material: "Engineered wood with laminate finish",
    budget: "450000",
    expectedCompletion: "2026-04-15",
    status: "negotiation",
    priority: "high",
    assignedUserId: "u1",
    assignedUserName: "Amit Kumar Sharma",
    source: "website",
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "e5",
    number: "AF-E-2026-0005",
    customerId: "c5",
    customerName: "Neha Sharma",
    service: "Furniture Restoration",
    category: "repair",
    requirement: "Restore antique dining table and 6 chairs",
    description: "Family heirloom, 40 years old. Needs polishing, minor repairs, and re-upholstery of chairs.",
    budget: "35000",
    expectedCompletion: "2026-02-10",
    status: "contacted",
    priority: "medium",
    assignedUserId: "u3",
    assignedUserName: "Rahul Verma",
    followUpDate: "2026-01-18",
    source: "referral",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "e6",
    number: "AF-E-2026-0006",
    customerId: "c6",
    customerName: "Rajesh Agarwal",
    service: "Interior Woodwork",
    category: "construction",
    requirement: "Complete woodwork for 8 hotel rooms",
    description: "Beds, wardrobes, TV units, study tables, and doors for 8 rooms in new hotel wing.",
    dimensions: "Each room 14×12 ft",
    material: "Commercial ply with veneer finish",
    budget: "780000",
    expectedCompletion: "2026-06-30",
    status: "followup",
    priority: "high",
    assignedUserId: "u1",
    assignedUserName: "Amit Kumar Sharma",
    followUpDate: "2026-01-22",
    source: "website",
    createdAt: new Date(Date.now() - 86400000 * 14).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: "e7",
    number: "AF-E-2026-0007",
    customerId: "c7",
    customerName: "Kavita Bose",
    service: "Bed Making",
    category: "furniture",
    requirement: "King-size storage bed with hydraulic lift",
    description: "Solid wood king bed with full hydraulic storage. Headboard with side shelves.",
    budget: "55000",
    status: "new",
    priority: "low",
    assignedUserId: "u3",
    assignedUserName: "Rahul Verma",
    source: "website",
    createdAt: new Date(Date.now() - 3600000 * 8).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    id: "e8",
    number: "AF-E-2026-0008",
    customerId: "c8",
    customerName: "Suresh Thapa",
    service: "Furniture Polishing",
    category: "repair",
    requirement: "Polishing for 4-door wooden almirah",
    description: "French polish renewal. Minor scratches to be filled.",
    budget: "8000",
    status: "new",
    priority: "low",
    source: "walk-in",
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: "e9",
    number: "AF-E-2026-0009",
    customerId: "c1",
    customerName: "Rahul Sharma",
    service: "Kitchen Cabinets",
    category: "furniture",
    requirement: "Small pantry unit for kitchen extension",
    description: "Wall mounted pantry with 4 shelves and pull-out drawers.",
    budget: "25000",
    status: "completed",
    priority: "medium",
    assignedUserId: "u2",
    assignedUserName: "Priya Das",
    source: "referral",
    createdAt: new Date(Date.now() - 86400000 * 45).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 20).toISOString(),
  },
  {
    id: "e10",
    number: "AF-E-2026-0010",
    customerId: "c2",
    customerName: "Priya Das",
    service: "Doors and Windows",
    category: "construction",
    requirement: "Main door and 3 interior doors for new house",
    description: "Main door with carving, interior flush doors with wooden frames.",
    budget: "95000",
    status: "rejected",
    priority: "medium",
    assignedUserId: "u2",
    assignedUserName: "Priya Das",
    source: "referral",
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 15).toISOString(),
  },
  {
    id: "e11",
    number: "AF-E-2026-0011",
    customerId: "c3",
    customerName: "Amit Roy",
    service: "TV Unit",
    category: "furniture",
    requirement: "Wall-mounted TV unit with display shelves",
    description: "For 65-inch TV. Need storage for books and display items.",
    budget: "32000",
    status: "quoted",
    priority: "medium",
    assignedUserId: "u3",
    assignedUserName: "Rahul Verma",
    source: "website",
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "e12",
    number: "AF-E-2026-0012",
    customerId: "c4",
    customerName: "Sanjay Gupta",
    service: "Conference Table",
    category: "furniture",
    requirement: "Large conference table for board room",
    description: "12-seater conference table with cable management.",
    budget: "120000",
    status: "approved",
    priority: "high",
    assignedUserId: "u1",
    assignedUserName: "Amit Kumar Sharma",
    source: "website",
    createdAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
];

/* ============================================================
 * QUOTATIONS
 * ============================================================ */

export const quotations: Quotation[] = [
  {
    id: "q1",
    number: "AF-Q-2026-0001",
    enquiryId: "e1",
    customerId: "c1",
    customerName: "Rahul Sharma",
    projectName: "Master Bedroom Wardrobe",
    subtotal: "75000",
    discount: "2000",
    taxRate: "18",
    taxAmount: "13140",
    total: "86140",
    validityDays: 15,
    validUntil: "2026-01-30",
    paymentTerms: "40% advance, 40% on manufacturing completion, 20% on installation",
    deliveryTerms: "4-6 weeks from advance payment",
    status: "sent",
    createdBy: "u2",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    items: [
      { name: "Sliding Wardrobe Frame (8×7 ft)", quantity: "1", unit: "piece", unitPrice: "45000", total: "45000" },
      { name: "Internal Shelving & Drawers", quantity: "1", unit: "set", unitPrice: "15000", total: "15000" },
      { name: "Mirror Panel", quantity: "1", unit: "piece", unitPrice: "5000", total: "5000" },
      { name: "LED Lighting Kit", quantity: "1", unit: "set", unitPrice: "4500", total: "4500" },
      { name: "Brass Handles & Hardware", quantity: "1", unit: "set", unitPrice: "3500", total: "3500" },
      { name: "Polishing & Finish", quantity: "1", unit: "job", unitPrice: "2000", total: "2000" },
    ],
  },
  {
    id: "q2",
    number: "AF-Q-2026-0002",
    enquiryId: "e2",
    customerId: "c2",
    customerName: "Priya Das",
    projectName: "Modular Kitchen - Das Residence",
    subtotal: "265000",
    discount: "5000",
    taxRate: "18",
    taxAmount: "46800",
    total: "306800",
    validUntil: "2026-02-15",
    paymentTerms: "50% advance, 30% midway, 20% on completion",
    status: "accepted",
    createdBy: "u2",
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    acceptedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    items: [
      { name: "Base Cabinets (L-shape)", quantity: "1", unit: "set", unitPrice: "95000", total: "95000" },
      { name: "Wall Cabinets", quantity: "1", unit: "set", unitPrice: "65000", total: "65000" },
      { name: "Tall Unit (Pantry)", quantity: "1", unit: "piece", unitPrice: "35000", total: "35000" },
      { name: "Breakfast Counter", quantity: "1", unit: "piece", unitPrice: "28000", total: "28000" },
      { name: "Acrylic Shutters", quantity: "1", unit: "set", unitPrice: "32000", total: "32000" },
      { name: "Hardware & Accessories", quantity: "1", unit: "set", unitPrice: "10000", total: "10000" },
    ],
  },
  {
    id: "q3",
    number: "AF-Q-2026-0003",
    enquiryId: "e4",
    customerId: "c4",
    customerName: "Sanjay Gupta",
    projectName: "Gupta Enterprises Office Setup",
    subtotal: "425000",
    discount: "15000",
    taxRate: "18",
    taxAmount: "73800",
    total: "483800",
    validUntil: "2026-02-10",
    status: "negotiation",
    createdBy: "u1",
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    items: [
      { name: "Workstations (20 units)", quantity: "20", unit: "piece", unitPrice: "12500", total: "250000" },
      { name: "Executive Cabin Set", quantity: "1", unit: "set", unitPrice: "75000", total: "75000" },
      { name: "Conference Table (10-seater)", quantity: "1", unit: "piece", unitPrice: "55000", total: "55000" },
      { name: "Reception Desk", quantity: "1", unit: "piece", unitPrice: "30000", total: "30000" },
      { name: "Storage Units", quantity: "5", unit: "piece", unitPrice: "3000", total: "15000" },
    ],
  },
  {
    id: "q4",
    number: "AF-Q-2026-0004",
    enquiryId: "e11",
    customerId: "c3",
    customerName: "Amit Roy",
    projectName: "TV Unit - Roy Residence",
    subtotal: "28000",
    discount: "0",
    taxRate: "18",
    taxAmount: "5040",
    total: "33040",
    validUntil: "2026-02-05",
    status: "sent",
    createdBy: "u3",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    items: [
      { name: "Wall-mounted TV Cabinet", quantity: "1", unit: "piece", unitPrice: "18000", total: "18000" },
      { name: "Display Shelves", quantity: "4", unit: "piece", unitPrice: "2000", total: "8000" },
      { name: "LED Back-lighting", quantity: "1", unit: "set", unitPrice: "2000", total: "2000" },
    ],
  },
  {
    id: "q5",
    number: "AF-Q-2026-0005",
    enquiryId: "e12",
    customerId: "c4",
    customerName: "Sanjay Gupta",
    projectName: "Board Room Conference Table",
    subtotal: "110000",
    discount: "5000",
    taxRate: "18",
    taxAmount: "18900",
    total: "123900",
    validUntil: "2026-01-28",
    status: "accepted",
    createdBy: "u1",
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    acceptedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    items: [
      { name: "12-Seater Conference Table", quantity: "1", unit: "piece", unitPrice: "95000", total: "95000" },
      { name: "Cable Management System", quantity: "1", unit: "set", unitPrice: "8000", total: "8000" },
      { name: "Leather Chair Pads", quantity: "12", unit: "piece", unitPrice: "583", total: "7000" },
    ],
  },
];

/* ============================================================
 * PROJECTS
 * ============================================================ */

export const projects: Project[] = [
  {
    id: "p1",
    number: "AF-P-2026-0001",
    name: "Modular Kitchen - Das Residence",
    customerId: "c2",
    customerName: "Priya Das",
    quotationId: "q2",
    type: "modular_kitchen",
    location: "Sevoke Road, Siliguri",
    description: "L-shaped modular kitchen with acrylic finish and breakfast counter",
    value: "306800",
    startDate: "2026-01-05",
    expectedCompletion: "2026-03-30",
    status: "manufacturing",
    progress: 55,
    assignedManagerId: "u2",
    assignedManagerName: "Priya Das",
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: "p2",
    number: "AF-P-2026-0002",
    name: "Board Room Conference Table",
    customerId: "c4",
    customerName: "Sanjay Gupta",
    quotationId: "q5",
    type: "office_furniture",
    location: "Burdwan Road, Siliguri",
    description: "12-seater conference table with cable management",
    value: "123900",
    startDate: "2025-12-28",
    expectedCompletion: "2026-02-05",
    status: "installation",
    progress: 85,
    assignedManagerId: "u1",
    assignedManagerName: "Amit Kumar Sharma",
    createdAt: new Date(Date.now() - 86400000 * 15).toISOString(),
  },
  {
    id: "p3",
    number: "AF-P-2026-0003",
    name: "Pantry Unit - Sharma Residence",
    customerId: "c1",
    customerName: "Rahul Sharma",
    type: "kitchen_cabinets",
    location: "Hill Cart Road, Siliguri",
    value: "25000",
    startDate: "2025-12-01",
    expectedCompletion: "2025-12-20",
    actualCompletion: "2025-12-18",
    status: "completed",
    progress: 100,
    assignedManagerId: "u2",
    assignedManagerName: "Priya Das",
    createdAt: new Date(Date.now() - 86400000 * 40).toISOString(),
  },
  {
    id: "p4",
    number: "AF-P-2026-0004",
    name: "Hotel Room Woodwork - Agarwal Hotels",
    customerId: "c6",
    customerName: "Rajesh Agarwal",
    type: "interior_woodwork",
    location: "Hospital Road, Jalpaiguri",
    description: "Complete woodwork for 8 hotel rooms - beds, wardrobes, TV units, doors",
    value: "780000",
    startDate: "2026-01-15",
    expectedCompletion: "2026-06-30",
    status: "design",
    progress: 15,
    assignedManagerId: "u1",
    assignedManagerName: "Amit Kumar Sharma",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "p5",
    number: "AF-P-2026-0005",
    name: "Antique Dining Set Restoration",
    customerId: "c5",
    customerName: "Neha Sharma",
    type: "restoration",
    location: "Pradhan Nagar, Siliguri",
    value: "35000",
    startDate: "2026-01-10",
    expectedCompletion: "2026-02-10",
    status: "manufacturing",
    progress: 40,
    assignedManagerId: "u5",
    assignedManagerName: "Bikash Rai",
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "p6",
    number: "AF-P-2026-0006",
    name: "Custom Bed - Roy Residence",
    customerId: "c3",
    customerName: "Amit Roy",
    type: "bedroom_furniture",
    location: "Hakim Para, Siliguri",
    value: "48000",
    startDate: "2025-11-15",
    expectedCompletion: "2025-12-20",
    actualCompletion: "2025-12-22",
    status: "completed",
    progress: 100,
    assignedManagerId: "u2",
    assignedManagerName: "Priya Das",
    createdAt: new Date(Date.now() - 86400000 * 60).toISOString(),
  },
  {
    id: "p7",
    number: "AF-P-2026-0007",
    name: "Office Setup - Gupta Enterprises",
    customerId: "c4",
    customerName: "Sanjay Gupta",
    type: "office_furniture",
    location: "Burdwan Road, Siliguri",
    value: "483800",
    status: "planning",
    progress: 5,
    assignedManagerId: "u1",
    assignedManagerName: "Amit Kumar Sharma",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "p8",
    number: "AF-P-2026-0008",
    name: "Custom Sofa Set",
    customerId: "c1",
    customerName: "Rahul Sharma",
    type: "living_room",
    location: "Hill Cart Road, Siliguri",
    value: "65000",
    startDate: "2025-10-10",
    expectedCompletion: "2025-11-15",
    actualCompletion: "2025-11-20",
    status: "completed",
    progress: 100,
    assignedManagerId: "u5",
    assignedManagerName: "Bikash Rai",
    createdAt: new Date(Date.now() - 86400000 * 90).toISOString(),
  },
];

/* ============================================================
 * TASKS
 * ============================================================ */

export const tasks: Task[] = [
  {
    id: "t1",
    name: "Site measurement for Das kitchen",
    projectId: "p1",
    projectName: "Modular Kitchen - Das Residence",
    customerId: "c2",
    customerName: "Priya Das",
    assignedUserId: "u2",
    assignedUserName: "Priya Das",
    dueDate: new Date(Date.now() + 86400000 * 2).toISOString(),
    priority: "high",
    status: "in_progress",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "t2",
    name: "Follow up with Rahul Sharma on wardrobe quote",
    enquiryId: "e1",
    customerId: "c1",
    customerName: "Rahul Sharma",
    assignedUserId: "u2",
    assignedUserName: "Priya Das",
    dueDate: new Date().toISOString(),
    priority: "urgent",
    status: "pending",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "t3",
    name: "Install conference table at Gupta office",
    projectId: "p2",
    projectName: "Board Room Conference Table",
    assignedUserId: "u5",
    assignedUserName: "Bikash Rai",
    dueDate: new Date(Date.now() + 86400000 * 4).toISOString(),
    priority: "high",
    status: "pending",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "t4",
    name: "Call Kavita Bose for bed requirements",
    enquiryId: "e7",
    customerId: "c7",
    customerName: "Kavita Bose",
    assignedUserId: "u3",
    assignedUserName: "Rahul Verma",
    dueDate: new Date().toISOString(),
    priority: "medium",
    status: "pending",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "t5",
    name: "Order teak wood for wardrobe project",
    projectId: "p1",
    assignedUserId: "u5",
    assignedUserName: "Bikash Rai",
    dueDate: new Date(Date.now() + 86400000).toISOString(),
    priority: "high",
    status: "in_progress",
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "t6",
    name: "Send advance payment reminder to Sanjay Gupta",
    customerId: "c4",
    customerName: "Sanjay Gupta",
    assignedUserId: "u4",
    assignedUserName: "Sneha Gupta",
    dueDate: new Date().toISOString(),
    priority: "medium",
    status: "pending",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "t7",
    name: "Final polish on antique dining set",
    projectId: "p5",
    assignedUserId: "u5",
    assignedUserName: "Bikash Rai",
    dueDate: new Date(Date.now() + 86400000 * 7).toISOString(),
    priority: "medium",
    status: "pending",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "t8",
    name: "Prepare design drawings for hotel rooms",
    projectId: "p4",
    assignedUserId: "u1",
    assignedUserName: "Amit Kumar Sharma",
    dueDate: new Date(Date.now() + 86400000 * 5).toISOString(),
    priority: "high",
    status: "in_progress",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "t9",
    name: "Visit Suresh Thapa for almirah inspection",
    enquiryId: "e8",
    customerId: "c8",
    customerName: "Suresh Thapa",
    assignedUserId: "u3",
    assignedUserName: "Rahul Verma",
    dueDate: new Date(Date.now() + 86400000 * 3).toISOString(),
    priority: "low",
    status: "pending",
    createdAt: new Date(Date.now() - 3600000 * 6).toISOString(),
  },
  {
    id: "t10",
    name: "Complete pantry unit installation",
    projectId: "p3",
    assignedUserId: "u5",
    assignedUserName: "Bikash Rai",
    dueDate: new Date(Date.now() - 86400000 * 20).toISOString(),
    priority: "high",
    status: "completed",
    createdAt: new Date(Date.now() - 86400000 * 25).toISOString(),
    completedAt: new Date(Date.now() - 86400000 * 20).toISOString(),
  },
];

/* ============================================================
 * PAYMENTS
 * ============================================================ */

export const payments: Payment[] = [
  {
    id: "pay1",
    number: "AF-PAY-2026-0001",
    customerId: "c2",
    customerName: "Priya Das",
    projectId: "p1",
    projectName: "Modular Kitchen - Das Residence",
    invoiceId: "inv1",
    amount: "153400",
    method: "bank",
    referenceNumber: "NEFT/2026/001245",
    paymentDate: new Date(Date.now() - 86400000 * 5).toISOString(),
    status: "paid",
    notes: "50% advance payment",
    receivedBy: "u4",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "pay2",
    number: "AF-PAY-2026-0002",
    customerId: "c4",
    customerName: "Sanjay Gupta",
    projectId: "p2",
    projectName: "Board Room Conference Table",
    invoiceId: "inv2",
    amount: "61950",
    method: "upi",
    referenceNumber: "UPI/874512369",
    paymentDate: new Date(Date.now() - 86400000 * 8).toISOString(),
    status: "paid",
    notes: "50% advance",
    receivedBy: "u4",
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: "pay3",
    number: "AF-PAY-2026-0003",
    customerId: "c1",
    customerName: "Rahul Sharma",
    projectId: "p3",
    projectName: "Pantry Unit - Sharma Residence",
    amount: "25000",
    method: "cash",
    paymentDate: new Date(Date.now() - 86400000 * 22).toISOString(),
    status: "paid",
    notes: "Full payment on completion",
    receivedBy: "u4",
    createdAt: new Date(Date.now() - 86400000 * 22).toISOString(),
  },
  {
    id: "pay4",
    number: "AF-PAY-2026-0004",
    customerId: "c4",
    customerName: "Sanjay Gupta",
    projectId: "p2",
    projectName: "Board Room Conference Table",
    amount: "40000",
    method: "bank",
    referenceNumber: "NEFT/2026/001890",
    paymentDate: new Date(Date.now() - 86400000 * 3).toISOString(),
    status: "paid",
    notes: "Midway payment",
    receivedBy: "u4",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "pay5",
    number: "AF-PAY-2026-0005",
    customerId: "c3",
    customerName: "Amit Roy",
    projectId: "p6",
    amount: "48000",
    method: "upi",
    paymentDate: new Date(Date.now() - 86400000 * 40).toISOString(),
    status: "paid",
    receivedBy: "u4",
    createdAt: new Date(Date.now() - 86400000 * 40).toISOString(),
  },
  {
    id: "pay6",
    number: "AF-PAY-2026-0006",
    customerId: "c5",
    customerName: "Neha Sharma",
    projectId: "p5",
    amount: "17500",
    method: "cash",
    paymentDate: new Date(Date.now() - 86400000 * 4).toISOString(),
    status: "paid",
    notes: "50% advance for restoration work",
    receivedBy: "u4",
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "pay7",
    number: "AF-PAY-2026-0007",
    customerId: "c1",
    customerName: "Rahul Sharma",
    projectId: "p8",
    amount: "65000",
    method: "bank",
    paymentDate: new Date(Date.now() - 86400000 * 75).toISOString(),
    status: "paid",
    receivedBy: "u4",
    createdAt: new Date(Date.now() - 86400000 * 75).toISOString(),
  },
  {
    id: "pay8",
    number: "AF-PAY-2026-0008",
    customerId: "c4",
    customerName: "Sanjay Gupta",
    projectId: "p2",
    amount: "21950",
    method: "pending",
    paymentDate: new Date(Date.now() + 86400000 * 3).toISOString(),
    status: "pending",
    notes: "Final balance due on installation",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

/* ============================================================
 * INVOICES
 * ============================================================ */

export const invoices: Invoice[] = [
  {
    id: "inv1",
    number: "AF-INV-2026-0001",
    customerId: "c2",
    customerName: "Priya Das",
    projectId: "p1",
    projectName: "Modular Kitchen - Das Residence",
    subtotal: "265000",
    discount: "5000",
    taxRate: "18",
    taxAmount: "46800",
    total: "306800",
    amountPaid: "153400",
    dueDate: new Date(Date.now() + 86400000 * 15).toISOString(),
    status: "partial",
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: "inv2",
    number: "AF-INV-2026-0002",
    customerId: "c4",
    customerName: "Sanjay Gupta",
    projectId: "p2",
    projectName: "Board Room Conference Table",
    subtotal: "110000",
    discount: "5000",
    taxRate: "18",
    taxAmount: "18900",
    total: "123900",
    amountPaid: "101950",
    dueDate: new Date(Date.now() + 86400000 * 5).toISOString(),
    status: "partial",
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: "inv3",
    number: "AF-INV-2026-0003",
    customerId: "c1",
    customerName: "Rahul Sharma",
    projectId: "p3",
    total: "25000",
    amountPaid: "25000",
    status: "paid",
    createdAt: new Date(Date.now() - 86400000 * 25).toISOString(),
  },
  {
    id: "inv4",
    number: "AF-INV-2026-0004",
    customerId: "c3",
    customerName: "Amit Roy",
    projectId: "p6",
    total: "48000",
    amountPaid: "48000",
    status: "paid",
    createdAt: new Date(Date.now() - 86400000 * 45).toISOString(),
  },
  {
    id: "inv5",
    number: "AF-INV-2026-0005",
    customerId: "c5",
    customerName: "Neha Sharma",
    projectId: "p5",
    total: "35000",
    amountPaid: "17500",
    dueDate: new Date(Date.now() + 86400000 * 20).toISOString(),
    status: "partial",
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: "inv6",
    number: "AF-INV-2026-0006",
    customerId: "c1",
    customerName: "Rahul Sharma",
    projectId: "p8",
    total: "65000",
    amountPaid: "65000",
    status: "paid",
    createdAt: new Date(Date.now() - 86400000 * 80).toISOString(),
  },
];

/* ============================================================
 * CALENDAR EVENTS
 * ============================================================ */

export const calendarEvents: CalendarEvent[] = [
  {
    id: "cal1",
    title: "Site visit - Das kitchen",
    type: "measurement",
    customerId: "c2",
    customerName: "Priya Das",
    assignedUserId: "u2",
    startsAt: new Date(Date.now() + 86400000 * 2).toISOString(),
    allDay: false,
    location: "Sevoke Road, Siliguri",
  },
  {
    id: "cal2",
    title: "Follow up - Rahul wardrobe",
    type: "followup",
    customerId: "c1",
    customerName: "Rahul Sharma",
    assignedUserId: "u2",
    startsAt: new Date(Date.now() + 3600000 * 4).toISOString(),
  },
  {
    id: "cal3",
    title: "Installation - Conference table",
    type: "installation",
    projectId: "p2",
    customerName: "Sanjay Gupta",
    assignedUserId: "u5",
    startsAt: new Date(Date.now() + 86400000 * 4).toISOString(),
    location: "Gupta Enterprises, Burdwan Road",
  },
  {
    id: "cal4",
    title: "Client meeting - Agarwal Hotels",
    type: "meeting",
    customerId: "c6",
    customerName: "Rajesh Agarwal",
    assignedUserId: "u1",
    startsAt: new Date(Date.now() + 86400000 * 1).toISOString(),
    location: "Agarwal Hotels, Jalpaiguri",
  },
  {
    id: "cal5",
    title: "Payment reminder - Gupta",
    type: "payment_reminder",
    customerId: "c4",
    customerName: "Sanjay Gupta",
    startsAt: new Date(Date.now() + 86400000 * 3).toISOString(),
  },
  {
    id: "cal6",
    title: "Workshop review",
    type: "meeting",
    startsAt: new Date(Date.now() + 86400000).toISOString(),
    allDay: false,
  },
  {
    id: "cal7",
    title: "Visit - Kavita Bose",
    type: "visit",
    customerId: "c7",
    customerName: "Kavita Bose",
    startsAt: new Date(Date.now() + 86400000 * 2 + 3600000 * 3).toISOString(),
    location: "Darjeeling",
  },
  {
    id: "cal8",
    title: "Project deadline - Das Kitchen Phase 1",
    type: "deadline",
    projectId: "p1",
    startsAt: new Date(Date.now() + 86400000 * 10).toISOString(),
    allDay: true,
  },
];

/* ============================================================
 * COMMUNICATIONS
 * ============================================================ */

export const communications: Communication[] = [
  {
    id: "com1",
    customerId: "c1",
    customerName: "Rahul Sharma",
    enquiryId: "e1",
    staffId: "u2",
    staffName: "Priya Das",
    type: "phone",
    direction: "outbound",
    summary: "Discussed wardrobe dimensions and material options. Customer prefers teak finish.",
    occurredAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "com2",
    customerId: "c2",
    customerName: "Priya Das",
    projectId: "p1",
    staffId: "u2",
    staffName: "Priya Das",
    type: "visit",
    direction: "outbound",
    summary: "Site measurement completed. All dimensions recorded. Photos taken for design reference.",
    occurredAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "com3",
    customerId: "c4",
    customerName: "Sanjay Gupta",
    staffId: "u1",
    staffName: "Amit Kumar Sharma",
    type: "email",
    direction: "inbound",
    subject: "Revised quote request",
    summary: "Client requested discount on bulk order for 20 workstations.",
    occurredAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "com4",
    customerId: "c5",
    customerName: "Neha Sharma",
    enquiryId: "e5",
    staffId: "u3",
    staffName: "Rahul Verma",
    type: "whatsapp",
    direction: "inbound",
    summary: "Shared photos of antique dining set for initial assessment.",
    occurredAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "com5",
    customerId: "c6",
    customerName: "Rajesh Agarwal",
    staffId: "u1",
    staffName: "Amit Kumar Sharma",
    type: "phone",
    direction: "outbound",
    summary: "Initial discussion about hotel room woodwork requirements. Scheduled site visit.",
    occurredAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
];

/* ============================================================
 * DOCUMENTS
 * ============================================================ */

export const documents: Document[] = [
  {
    id: "d1",
    name: "Wardrobe Quotation - Sharma",
    fileName: "AF-Q-2026-0001.pdf",
    fileUrl: "#",
    category: "quotation",
    customerId: "c1",
    enquiryId: "e1",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "d2",
    name: "Kitchen Design Drawings",
    fileName: "das-kitchen-design.pdf",
    fileUrl: "#",
    category: "design",
    customerId: "c2",
    projectId: "p1",
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: "d3",
    name: "Site Measurement Report",
    fileName: "das-kitchen-measurement.pdf",
    fileUrl: "#",
    category: "measurement",
    customerId: "c2",
    projectId: "p1",
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: "d4",
    name: "Service Agreement - Agarwal Hotels",
    fileName: "agarwal-agreement.pdf",
    fileUrl: "#",
    category: "agreement",
    customerId: "c6",
    projectId: "p4",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "d5",
    name: "Antique Dining Set Photos",
    fileName: "dining-set-before.jpg",
    fileUrl: "#",
    category: "customer_attachment",
    customerId: "c5",
    enquiryId: "e5",
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "d6",
    name: "Invoice - Pantry Unit",
    fileName: "AF-INV-2026-0003.pdf",
    fileUrl: "#",
    category: "invoice",
    customerId: "c1",
    projectId: "p3",
    createdAt: new Date(Date.now() - 86400000 * 25).toISOString(),
  },
];

/* ============================================================
 * ACTIVITY LOG
 * ============================================================ */

export const activityLogs: ActivityLog[] = [
  {
    id: "al1",
    userId: "u1",
    userName: "Amit Kumar Sharma",
    action: "user.login",
    description: "Logged in successfully",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "al2",
    userId: "u2",
    userName: "Priya Das",
    action: "enquiry.created",
    resourceType: "enquiry",
    resourceId: "e7",
    description: "Created enquiry AF-E-2026-0007 for Kavita Bose",
    createdAt: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    id: "al3",
    userId: "u3",
    userName: "Rahul Verma",
    action: "quotation.sent",
    resourceType: "quotation",
    resourceId: "q4",
    description: "Sent quotation AF-Q-2026-0004 to Amit Roy",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "al4",
    userId: "u2",
    userName: "Priya Das",
    action: "enquiry.status_changed",
    resourceType: "enquiry",
    resourceId: "e1",
    description: "Changed enquiry status from 'contacted' to 'quoted'",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "al5",
    userId: "u4",
    userName: "Sneha Gupta",
    action: "payment.recorded",
    resourceType: "payment",
    resourceId: "pay4",
    description: "Recorded payment ₹40,000 from Sanjay Gupta",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "al6",
    userId: "u2",
    userName: "Priya Das",
    action: "project.status_changed",
    resourceType: "project",
    resourceId: "p1",
    description: "Updated project progress to 55% - moved to manufacturing stage",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "al7",
    userId: "u5",
    userName: "Bikash Rai",
    action: "task.completed",
    resourceType: "task",
    resourceId: "t10",
    description: "Completed task 'Pantry unit installation'",
    createdAt: new Date(Date.now() - 86400000 * 20).toISOString(),
  },
  {
    id: "al8",
    userId: "u1",
    userName: "Amit Kumar Sharma",
    action: "quotation.accepted",
    resourceType: "quotation",
    resourceId: "q5",
    description: "Quotation AF-Q-2026-0005 accepted by Sanjay Gupta",
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: "al9",
    userId: "u3",
    userName: "Rahul Verma",
    action: "customer.created",
    resourceType: "customer",
    resourceId: "c8",
    description: "Created new customer Suresh Thapa",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "al10",
    userId: "u2",
    userName: "Priya Das",
    action: "document.uploaded",
    resourceType: "document",
    resourceId: "d3",
    description: "Uploaded measurement report for Das kitchen project",
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
];

/* ============================================================
 * NOTIFICATIONS
 * ============================================================ */

export const notifications: Notification[] = [
  {
    id: "n1",
    userId: "u1",
    title: "New enquiry received",
    message: "Suresh Thapa submitted a polishing enquiry through the website",
    type: "info",
    link: "/admin/enquiries/e8",
    read: false,
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: "n2",
    userId: "u1",
    title: "Quotation accepted",
    message: "Sanjay Gupta accepted the board room conference table quotation",
    type: "success",
    link: "/admin/quotations/q5",
    read: false,
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: "n3",
    userId: "u1",
    title: "Follow-up due today",
    message: "You have 3 customer follow-ups scheduled for today",
    type: "warning",
    link: "/admin/tasks",
    read: false,
    createdAt: new Date(Date.now() - 3600000 * 6).toISOString(),
  },
  {
    id: "n4",
    userId: "u1",
    title: "Payment received",
    message: "₹40,000 received from Sanjay Gupta for conference table project",
    type: "success",
    link: "/admin/payments",
    read: true,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "n5",
    userId: "u1",
    title: "Project deadline approaching",
    message: "Board Room Conference Table installation due in 4 days",
    type: "warning",
    link: "/admin/projects/p2",
    read: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

/* ============================================================
 * DASHBOARD STATS (derived)
 * ============================================================ */

export function getDashboardStats() {
  const newEnquiries = enquiries.filter((e) => e.status === "new").length;
  const pendingQuotes = quotations.filter((q) => q.status === "draft" || q.status === "sent").length;
  const activeProjects = projects.filter((p) => !["completed", "cancelled"].includes(p.status)).length;
  const todaysTasks = tasks.filter((t) => {
    if (t.status === "completed" || t.status === "cancelled") return false;
    const due = new Date(t.dueDate);
    const today = new Date();
    return due.toDateString() === today.toDateString() || due < today;
  }).length;
  const newCustomers = customers.filter((c) => {
    const created = new Date(c.createdAt);
    const weekAgo = new Date(Date.now() - 86400000 * 7);
    return created > weekAgo;
  }).length;
  const outstanding = payments
    .filter((p) => p.status === "pending")
    .reduce((sum, p) => sum + parseFloat(p.amount), 0) +
    invoices
      .filter((i) => i.status === "partial" || i.status === "overdue" || i.status === "sent")
      .reduce((sum, i) => sum + (parseFloat(i.total) - parseFloat(i.amountPaid || "0")), 0);

  return {
    newEnquiries,
    pendingQuotes,
    activeProjects,
    todaysTasks,
    newCustomers,
    outstanding,
  };
}
